using ForwardDiff
using Interpolations
using NLsolve
using DataFrames
using LinearAlgebra
using PeriodicTable
using JLD
using DelimitedFiles
using SharedArrays
using LinearSolve
#using OptimizationOptimJL
#using Optimization
using Optim
